{
 "title": "Windows System Metrics",
 "description": "Monitor Windows systems via Telegraf and InfluxDB",
 "tags": [
  "Windows",
  "Telegraf",
  "InfluxDB"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM win_system WITH KEY=host"
   }
  ]
 },
 "panels": [
  {
   "title": "$Host - SWAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "$Host - Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "Host" },
  {
   "title": "$Host - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Host - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"%_Interrupt_Time\") as \"% Interrupt Time\", mean(\"%_Privileged_Time\") as \"% Privileged Time\", mean(\"%_Processor_Time\") as \"% Processor Time\", mean(\"%_User_Time\") as \"% User Time\" FROM \"win_cpu\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Privileged" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Processor" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_DPC_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% DPC" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Host - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pool Nonpaged Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pool paged Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Memory Usage Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Cache_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cache Faults persec" ], "type": "alias" }
      ],
      [
       { "params": [ "Demand_Zero_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Demand Zero Faults persec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page Faults persec" ], "type": "alias" }
      ],
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pages persec" ], "type": "alias" }
      ],
      [
       { "params": [ "Transition_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Transition Faults persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Disk Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Host - Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "instance" ], "type": "tag" },
      { "key": "path", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Percent_Free_Space\") AS \"% Free Space\" FROM \"win_disk\" WHERE \"host\" =~ /$Host$/ AND $timeFilter GROUP BY time($__interval), \"host\", instance",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Current Disk Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current Disk Queue Length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Disk Idle Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" },
      { "key": "path", "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"%_Idle_Time\") AS \"% Idle Time\" FROM \"win_disk\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval), \"host\", instance",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Host - Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host:  $tag_instance - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received persec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Sent persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - Network Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Packets_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packets Received persec" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packets Sent persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Host - Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Context_Switches_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Context Switches persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "$Host - System Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_instance - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(\"System_Calls_persec\") AS \"System Calls persec\" FROM \"win_system\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval), \"host\", instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_instance - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Calls_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System Calls persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}